let myjokes = [
  {
    category: "Programming",
    type: "single",
    joke: "Have a great weekend!\nI hope your code behaves the same on Monday as it did on Friday.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 44,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Saying that Java is nice because it works on every OS is like saying that anal sex is nice because it works on every gender.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 30,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 37,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Algorithm: A word used by programmers when they don't want to explain how their code works.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 51,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Java is like Alzheimer's, it starts off slow, but eventually, your memory is gone.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 27,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "I've got a really good UDP joke to tell you but I don’t know if you'll get it.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 0,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: '"Knock, knock."\n"Who\'s there?"\n\n[very long pause]\n\n"Java."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 36,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "// This line doesn't actually do anything, but the code stops working when I delete it.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 12,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "UDP is better in the COVID era since it avoids unnecessary handshakes.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 259,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Four engineers get into a car. The car won\'t start.\nThe Mechanical engineer says "It\'s a broken starter".\nThe Electrical engineer says "Dead battery".\nThe Chemical engineer says "Impurities in the gasoline".\nThe IT engineer says "Hey guys, I have an idea: How about we all get out of the car and get back in".',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 132,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "Oysters hate to give away their pearls because they are shellfish.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 90,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Java is like Alzheimer's, it starts off slow, but eventually, your memory is gone.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 27,
    safe: false,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Never date a baker. They're too kneady.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 271,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "My ex had an accident. I told the paramedics the wrong blood type for her. She'll finally experience what rejection is really like.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 152,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "I was struggling to figure out how lightning works, but then it struck me.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 220,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\'t worry about warnings; we only worry about errors."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 38,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A guy walks into a bar and asks for 1.4 root beers.\nThe bartender says "I\'ll have to charge you extra, that\'s a root beer float".\nThe guy says "In that case, better make it a double."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 2,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "To whoever stole my copy of Microsoft Office, I will find you. You have my Word!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 191,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "In Soviet Russia, gay sex gets you arrested. In America, getting arrested gets you gay sex.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    safe: false,
    id: 289,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "My husband and I were happy for 20 years. And then we met.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 273,
    lang: "en",
  },
];

// let index = Math.floor(Math.random() * myjokes.length - 1);
// joke.innerHTML = myjokes[index].joke;


// Get a reference to the button element
const changeJokeBtn = document.getElementById("change-joke-btn");

// Add a click event listener to the button
changeJokeBtn.addEventListener("click", () => {
  // Generate a random index to select a new joke
  const newIndex = Math.floor(Math.random() * myjokes.length);
  
  // Update the content of the joke elements with the new joke
  document.getElementById("joke").textContent = myjokes[newIndex].joke;
});


